### ISSUE TITLE
Problem when 'yarn run blendid -- build'

### ISSUE THREAD

**Issue by mralessio** [alexanderalmstrom/blendid-wp#1]
Thank you for your theme and really cool combination of WP, Blendid and Timber! 
I have an issue when run `yarn run blendid -- build` command. I'm working under Windows.
Getting this:
`$ "c:\OpenServer\domains\project.dev\web\app\themes\blendid-starter\node_modules\.bin\blendid" "build"
"c:\OpenServer\domains\project.dev\web\app\themes\blendid-starter\node_modules\.bin\blendid" "build" is not recognized as an internal or external command, operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

As it seems this occurs due to Yarn or Blendid, but perhaps you experienced such of a problem and know how to deal with it. Unfortunetly I've not found a solution yet.

**Comment by alexanderalmstrom** [comment]
Hello @mralessio 

This seems to be a Windows issue. I am running this in a Mac environment.

Found a thread about a similar problem here: https://www.bountysource.com/issues/47491298-yarn-run-blendid-init-error-code-1

Try to change the build script in `package.json` to the following

```
"build": "./node_modules/.bin/blendid build"
```

Then run

```
yarn run build
```
or
```
npm run build
```

**Comment by mralessio** [comment]
@alexanderalmstrom many thanks. Yup, this fixes things. 
Just putting here some links could be related to this issue:
Blendid: https://github.com/vigetlabs/blendid/issues/480
Yarn: https://github.com/yarnpkg/yarn/issues/3773

So for a final fix Windows users have to wait for Yarn update. Closing this issue, as apparently the solution is given.
